export const HOURS_IN_DAY = 24

export const MINUTES_IN_HOUR = 60

export const SECONDS_IN_MINUTE = 60
export const SECONDS_IN_HOUR = SECONDS_IN_MINUTE * MINUTES_IN_HOUR
export const SECONDS_IN_DAY = SECONDS_IN_HOUR * HOURS_IN_DAY

export const MILLISECONDS_IN_MINUTE = SECONDS_IN_MINUTE * 1000
export const MILLISECONDS_IN_HOUR = SECONDS_IN_HOUR * 1000
export const MILLISECONDS_IN_DAY = SECONDS_IN_DAY * 1000
